name: API Tests

on:
  # Run tests on Pull Requests
  pull_request:
    branches:
      - master
  # Allow manual trigger
  workflow_dispatch:
    inputs:
      testType:
        description: "Which tests to run (positive, negative, url_builder, deck_provider, all)"
        required: false
        default: "all"
  # Run all tests on any merge to main
  push:
    branches:
      - master

jobs:
  api-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        test-type: ["positive", "negative", "url_builder", "deck_provider", "all"]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.12

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run API Tests
      env:
        PYTHON_ENV: ci
      run: |
        case "${{ matrix.test-type }}" in
          positive)
            pytest tests/test_deck_of_cards_positive_scenarios.py --html=report_positive.html --self-contained-html
            ;;
          negative)
            pytest tests/test_deck_of_cards_negative_scenarios.py --html=report_negative.html --self-contained-html
            ;;
          url_builder)
            pytest tests/test_url_builder.py --html=report_url_builder.html --self-contained-html
            ;;
          deck_provider)
            pytest tests/test_deck_provider.py --html=report_deck_provider.html --self-contained-html
            ;;
          all)
            pytest tests/ --html=report_all.html --self-contained-html
            ;;
          *)
            echo "Invalid test type"; exit 1
            ;;
        esac

    - name: Upload Test Report
      uses: actions/upload-artifact@v3
      with:
        name: test-report
        path: |
          report_positive.html
          report_negative.html
          report_url_builder.html
          report_deck_provider.html
          report_all.html
