name: API Tests

on:
  # Run tests on Pull Requests
  pull_request:
    branches:
      - main
  # Allow manual trigger
  workflow_dispatch:
    inputs:
      testType:
        description: "Which tests to run (positive, negative, all)"
        required: false
        default: "all"
  # Run all tests on any merge to main
  push:
    branches:
      - main

jobs:
  api-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        test-type: ["positive", "negative", "all"]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.12

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run API Tests
      env:
        PYTHON_ENV: ci
      run: |
        case "${{ matrix.test-type }}" in
          positive)
            pytest -m positive --html=report.html --self-contained-html
            ;;
          negative)
            pytest -m negative --html=report.html --self-contained-html
            ;;
          all)
            pytest --html=report.html --self-contained-html
            ;;
          *)
            echo "Invalid test type"; exit 1
            ;;
        esac

    - name: Upload Test Report
      uses: actions/upload-artifact@v3
      with:
        name: test-report
        path: report.html
