name: API Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  positive:
    name: Positive Tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.12

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run Positive Tests
      run: pytest tests/test_deck_of_cards_positive_scenarios.py --html=positive_report.html --self-contained-html

    - name: Upload Test Report
      uses: actions/upload-artifact@v4
      with:
        name: positive-test-report
        path: positive_report.html

  negative:
    name: Negative Tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.12

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run Negative Tests
      run: pytest tests/test_deck_of_cards_negative_scenarios.py --html=negative_report.html --self-contained-html

    - name: Upload Test Report
      uses: actions/upload-artifact@v4
      with:
        name: negative-test-report
        path: negative_report.html

  deck_provider:
    name: Deck Provider Tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.12

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run Deck Provider Tests
      run: pytest tests/test_deck_provider.py --html=deck_provider_report.html --self-contained-html

    - name: Upload Test Report
      uses: actions/upload-artifact@v4
      with:
        name: deck-provider-test-report
        path: deck_provider_report.html

  url_builder:
    name: URL Builder Tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.12

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run URL Builder Tests
      run: pytest tests/test_url_builder.py --html=url_builder_report.html --self-contained-html

    - name: Upload Test Report
      uses: actions/upload-artifact@v4
      with:
        name: url-builder-test-report
        path: url_builder_report.html

  aggregate-results:
    name: Aggregate Results
    needs: [positive, negative, deck_provider, url_builder]
    if: always()
    runs-on: ubuntu-latest
    steps:
    - name: Download all test reports
      uses: actions/download-artifact@v3
      with:
        path: ./reports

    - name: Combine Reports
      run: |
        mkdir -p combined_reports
        cp ./reports/* combined_reports/
        echo "Reports combined in the 'combined_reports' folder."

    - name: Upload Combined Reports
      uses: actions/upload-artifact@v4
      with:
        name: combined-test-reports
        path: combined_reports/
